version: "3.7"
services:
  app:
    build:
      args:
        user: simap
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: simap
    container_name: simap-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - simap

  db:
    image: mysql:8.0
    container_name: simap-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: simap
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: simap
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - simap

  nginx:
    image: nginx:alpine
    container_name: simap-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - simap

networks:
  simap:
    driver: bridge
